DROP DATABASE IF EXISTS scrapbook;
CREATE DATABASE scrapbook;
USE scrapbook;

CREATE TABLE users(
id INTEGER(10) AUTO_INCREMENT NOT NULL,
username varchar(100) NOT NULL,
pass varchar(100) NULL,
PRIMARY KEY (id)
);


CREATE TABLE files(
id INTEGER(10) AUTO_INCREMENT NOT NULL,
file_type varchar(100) NOT NULL,
file_name varchar(100) NULL,
upload_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (id)
);